/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingokulprojesicifttablolu;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mert
 */
public class FmCikis extends javax.swing.JFrame {
      DefaultTableModel model;
     DbGiris islemler = new DbGiris();
     Clock clock = new Clock();

    /**
     * Creates new form FmCikis
     */
     
     public void temizle()
     {
     TbSaat.setText("");
     TbAgirlik.setText("");
     
     TbTarih.setText("");
     TbPlaka.setText("");
     }
       public void aracGoruntule()
    {
        model.setRowCount(0);
        ArrayList<CikisAracBilgileri> araclar = new ArrayList<CikisAracBilgileri>();
        araclar = islemler.CikisAraclariGetir();
        
        if (araclar!=null) {
            for(CikisAracBilgileri item : araclar)
            {
             Object[] eklenecek = {item.getAracnumarasi(),item.getPlaka(),item.getGirisAgirligi(),item.getGirisSaati(),item.getGirisTarihi(),item.getSoför(),item.getCikisAgirligi(),item.getCikisSaati(),item.getCikisTarihi(),item.getKayiteden(),item.getMarka()};
             model.addRow(eklenecek);
            }
        }
        
    }
    public FmCikis() {
        initComponents();
        clock.Clock(lblSaatTarih);
          model = (DefaultTableModel)tableArac.getModel();
           lblKullanici.setText("Hoşgeldiniz.... "+FmLogin.SendUsername);
         aracGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableArac = new javax.swing.JTable();
        TbPlaka = new javax.swing.JTextField();
        TbAgirlik = new javax.swing.JTextField();
        TbTarih = new javax.swing.JTextField();
        TbSaat = new javax.swing.JTextField();
        btnKayit = new javax.swing.JButton();
        lblPlaka = new javax.swing.JLabel();
        lblAgirlik = new javax.swing.JLabel();
        lblSaat = new javax.swing.JLabel();
        lblTarih = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblKullanici = new javax.swing.JLabel();
        lblSaatTarih = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblEkran = new javax.swing.JLabel();
        lblCikis = new javax.swing.JLabel();
        lblRapor = new javax.swing.JLabel();
        lblSil = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));

        tableArac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Araç No", "Plaka", "Giriş Ağırlığı", "Giriş Saati", "Giriş Tarihi", "Şoför", "Çıkış Ağırlığı", "Çıkış Saati", "Çıkış Tarihi", "Kayıt Eden", "Marka"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableArac.getTableHeader().setReorderingAllowed(false);
        tableArac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAracMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableArac);

        btnKayit.setBackground(new java.awt.Color(54, 70, 78));
        btnKayit.setForeground(new java.awt.Color(255, 255, 255));
        btnKayit.setText("Kayıt");
        btnKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitActionPerformed(evt);
            }
        });

        lblPlaka.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlaka.setText("Plaka :");

        lblAgirlik.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAgirlik.setText("Çıkış Ağırlığı :");

        lblSaat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSaat.setText("Çıkış Saati :");

        lblTarih.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTarih.setText("Çıkış Tarihi :");

        jPanel1.setBackground(new java.awt.Color(54, 70, 78));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblKullanici.setForeground(new java.awt.Color(255, 255, 255));
        lblKullanici.setText("Kullanıcı :");

        lblSaatTarih.setForeground(new java.awt.Color(255, 255, 255));
        lblSaatTarih.setText("Saat/Tarih :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblKullanici, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSaatTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullanici)
                    .addComponent(lblSaatTarih)))
        );

        jPanel3.setBackground(new java.awt.Color(54, 70, 78));

        lblEkran.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEkran.setForeground(new java.awt.Color(255, 255, 255));
        lblEkran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swingokulprojesicifttablolu/icons8-home-36.png"))); // NOI18N
        lblEkran.setText("Ana Ekrana Dön");
        lblEkran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEkranMouseClicked(evt);
            }
        });

        lblCikis.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblCikis.setForeground(new java.awt.Color(255, 255, 255));
        lblCikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swingokulprojesicifttablolu/icons8-logout-rounded-left-64.png"))); // NOI18N
        lblCikis.setText("Giriş");
        lblCikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCikisMouseClicked(evt);
            }
        });

        lblRapor.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblRapor.setForeground(new java.awt.Color(255, 255, 255));
        lblRapor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swingokulprojesicifttablolu/icons8-business-report-64.png"))); // NOI18N
        lblRapor.setText("Rapor");
        lblRapor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRaporMouseClicked(evt);
            }
        });

        lblSil.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblSil.setForeground(new java.awt.Color(255, 255, 255));
        lblSil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swingokulprojesicifttablolu/icons8-delete-64.png"))); // NOI18N
        lblSil.setText("Sil");
        lblSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCikis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRapor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblEkran, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEkran, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRapor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSil, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swingokulprojesicifttablolu/Adsız2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAgirlik)
                                            .addComponent(lblSaat)
                                            .addComponent(lblPlaka)
                                            .addComponent(lblTarih))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TbPlaka)
                                            .addComponent(TbSaat)
                                            .addComponent(TbAgirlik)
                                            .addComponent(TbTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblPlaka)
                                            .addComponent(TbPlaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblAgirlik)
                                            .addComponent(TbAgirlik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TbSaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblSaat))
                                        .addGap(18, 18, 18)
                                        .addComponent(TbTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTarih))
                                .addGap(18, 18, 18)
                                .addComponent(btnKayit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitActionPerformed

        String plaka = TbPlaka.getText();
        int cikisAgirligi = Integer.parseInt(TbAgirlik.getText());
        String cikisSaati = TbSaat.getText();
        String cikisTarihi = TbTarih.getText();
        
        
        int selectedRow =  tableArac.getSelectedRow();
        
        if (selectedRow==-1) {
            
            if (model.getRowCount()==0) {
                
                JOptionPane.showMessageDialog(this, "Tablo Şu Anda Boş!");
            }
            else
            {
            JOptionPane.showMessageDialog(this, "Lütfen Güncellenecek Bir Araç Seçin!!");
            }
            
        }
        else
        {
        int id = (int)model.getValueAt(selectedRow, 0);
        
        islemler.aracGuncelle(id,plaka,cikisAgirligi,cikisSaati,cikisTarihi);
        
        aracGoruntule();
        JOptionPane.showMessageDialog(this, "Başarıyla Güncellendi!");
        temizle();
        
        }

        
       

        
    }//GEN-LAST:event_btnKayitActionPerformed

    private void tableAracMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAracMouseClicked
       
        int selectedRow = tableArac.getSelectedRow();
        
        TbPlaka.setText(model.getValueAt(selectedRow, 1).toString());
        TbAgirlik.setText(model.getValueAt(selectedRow, 6).toString());
        TbSaat.setText(model.getValueAt(selectedRow, 7).toString());
        TbTarih.setText(model.getValueAt(selectedRow, 8).toString());
      
        
        
    }//GEN-LAST:event_tableAracMouseClicked

    private void lblEkranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEkranMouseClicked
        FmHome home = new FmHome();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_lblEkranMouseClicked

    private void lblCikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCikisMouseClicked
        FmGiris giris = new FmGiris();
        this.setVisible(false);
        giris.setVisible(true);
    }//GEN-LAST:event_lblCikisMouseClicked

    private void lblRaporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRaporMouseClicked
        FmSorgu sorgu = new FmSorgu();
        this.setVisible(false);
        sorgu.setVisible(true);
    }//GEN-LAST:event_lblRaporMouseClicked

    private void lblSilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSilMouseClicked
        int selectedRow =  tableArac.getSelectedRow();

        if (selectedRow==-1) {

            if (model.getRowCount()==0) {

                JOptionPane.showMessageDialog(this, "Tablo Şu Anda Boş!");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Lütfen Silinecek Bir Araç Seçin!!");
            }

        }
        else
        {
            int id = (int)model.getValueAt(selectedRow, 0);

            islemler.aracSil(id);
            aracGoruntule();
            JOptionPane.showMessageDialog(this, "Başarıyla Silindi!");

        }
    }//GEN-LAST:event_lblSilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmCikis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmCikis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmCikis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmCikis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmCikis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TbAgirlik;
    private javax.swing.JTextField TbPlaka;
    private javax.swing.JTextField TbSaat;
    private javax.swing.JTextField TbTarih;
    private javax.swing.JButton btnKayit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgirlik;
    private javax.swing.JLabel lblCikis;
    private javax.swing.JLabel lblEkran;
    private javax.swing.JLabel lblKullanici;
    private javax.swing.JLabel lblPlaka;
    private javax.swing.JLabel lblRapor;
    private javax.swing.JLabel lblSaat;
    private javax.swing.JLabel lblSaatTarih;
    private javax.swing.JLabel lblSil;
    private javax.swing.JLabel lblTarih;
    private javax.swing.JTable tableArac;
    // End of variables declaration//GEN-END:variables
}
